platform :ios, '6.0'

target 'LIFXKit iOS Static Library' do
	platform :ios, '6.0'
	pod 'CocoaAsyncSocket', "~> 7.4"

end


target 'LIFXKit OS X Static Library' do
	platform :osx, '10.9'
	pod 'CocoaAsyncSocket', "~> 7.4"

end

